name: 'Check code coverage'
description: 'This GitHub action reads a code coverage report and fails if the actual code coverage is below a specified threshold.'
branding:
  color: 'blue'
  icon: 'layers'
inputs:
  report:
    description: 'The name of the code coverage report file'
    required: true
  required-percentage:
    description: 'The code coverage in percent (0-100) required to pass'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
